<?php

namespace AppBundle\Repository;

/**
 * ConversationLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationLineRepository extends \Doctrine\ORM\EntityRepository
{
}
